### ISSUE TITLE
Works for a short while and then doesn't?

### ISSUE THREAD

**Issue by shrewdlogarithm** [rbelnienk/OWON-OW18B-BLE-Connector#2]
Spotted this and decided to see if it would work for my B35T - and it does!!

For a short period only... :(

I installed the latest BLEAK package - ran your code and it listed my device AOK

First slight bug - the way you loop all devices and have that default address setup means that, unless the selected device is last, it will always take the default - I think there should be a "break" statement after the matched device is found perhaps???

Once it's selected it then shows a few packets of data from the meter - good news - but just a few seconds-worth and then it just stops reporrting anything else (I've left it for upto 10 mins - nothing happens) 

If you Ctrl-C - it reports another flurry of packets and then ends!?!?!?

I'm guessing this is a problem within Bleak and not your code perhaps???

Note: I've tested this meter using BLEConsole on Windows - some Android Apps AND using the B41T C++ code on GitHub and they all report the data correctly - so I don't think it's the meter itself 

It's a shame as I'd like a simple Python program which works on Windows (most use GATTTOOL which doesn't) so I was really hoping I could get yours/Bleak working!!??

Any ideas apprec!!

**Comment by shrewdlogarithm** [comment]
Aha - I should have looked closer - after 5 seconds the program will stop awaiting input - my bad

One other thing I noticed tho - you don't need to re-call the notify inside your loop so this

```
flag = True

        while flag:
            
            if flag:
                value = await client.start_notify(MODEL_NBR_UUID,decode)
            
```

Should be more like this

```
flag = True

        await client.start_notify(MODEL_NBR_UUID,decode)
        
        while flag:
            
```

Perhaps?

Thanks for pushing me in the right direction tho!

**Comment by rbelnienk** [comment]
So the initial problem doesn't exist right? Then i will close this point. I'm working on a new revision at the moment anyway, i will try to use your input. 

so i can add the B41T as supported model?

**Comment by shrewdlogarithm** [comment]
I have a B35T+ but the B41T software I found on Github (it's C++ but it implements all the bidirection controls and can control/download the data recordings if you're curious about those functions) works fine - so I'd say you can add both of those models 
They're actually renaming these meters but I doubt they'll be changing the BLE software so I'd guess all OWON meters which use BLE will use the same protocols/services/UUIDs (they definately use the same app/software!!)
Note: the input() statement you're using - checking for 'None' will never be true - at least on Windows - just hitting enter returns an empty string ("") and it does seem to stop the asyncio whilst it's waiting so it might not be the best solution...
You can actually check client.isConnected and have the user turn the meter off to stop the program (or check it to see if it's disconnected and reconnect) 
A user can just Ctrl-C/Ctrl-Break to stop it
Thanks again!    On Wednesday, 5 July 2023 at 07:26:38 BST, Rene Bersch ***@***.***> wrote:  
 
 


So the initial prolem doesnt exist right? Then i will close this point. Im working on a new revision at the moment anyway, i will try to use your input.

so i can add the B41T as supported model?
